dist: xenial
sudo: true
cache:
  - directories:
      - /var/lib/docker
env:
  global:
    - DOCKER_SERVER_HOST=docker.local
    - DOCKER_SERVER_PORT=5001
    - DOCKER_PROJECT_PATH=components/value_object

install:
  - export DOCKER_IMAGE_VERSION=`echo $TRAVIS_BRANCH | tr "[:upper:]" "[:lower:]" | sed "s/[^a-zA-Z0-9-]/-/g" | sed "s/-$//g" | tr -d '\n' | tr -d '\r'`
  - export DOCKER_IMAGE_TAG=$DOCKER_SERVER_HOST:$DOCKER_SERVER_PORT/$DOCKER_PROJECT_PATH/app_test:$DOCKER_IMAGE_VERSION
  - docker build . -f .docker/app_test/Dockerfile -t $DOCKER_IMAGE_TAG

script:
  - docker run $DOCKER_IMAGE_TAG vendor/bin/parallel-lint ./ --exclude vendor
  - docker run $DOCKER_IMAGE_TAG vendor/bin/phpstan analyse -l 6 -c phpstan.neon src tests
  - docker run $DOCKER_IMAGE_TAG vendor/bin/psalm --config=psalm.xml
  - docker run $DOCKER_IMAGE_TAG vendor/bin/ecs check src tests
  - docker run $DOCKER_IMAGE_TAG vendor/bin/phpmd src/ text phpmd.xml